### ISSUE TITLE
RARC packing

### ISSUE THREAD

**Issue by pho** [pho/WindViewer#1]
Right now, Wind Viewer just stores the offsets of the files inside the .arc files and write directly on those offsets.
Adding actors will increase the .dzr file size, which can't be done without unpacking and repacking the file

**Comment by pho** [comment]
Needs some more testing, i've seen some malformed files

**Comment by Matt-Hurd** [comment]
For whatever reason, some files seems to still be getting messed up. One file I noticed was Room0.arc in M_NewD2.

**Comment by pho** [comment]
The root node numFileEntries was being set incorrectly. Fixed with 4eaba9e090bf9b44a528b5b9593c46cccbd35c69
